<?php

// File generated from our OpenAPI spec

namespace GiveDonationBlock\Strauss\Stripe\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     *
     * @license MIT
     * Modified by Jason Adams on 03-March-2022 using Strauss.
     * @see https://github.com/BrianHenryIE/strauss
     */
    const mapping = [
        \GiveDonationBlock\Strauss\Stripe\Account::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Account::class,
        \GiveDonationBlock\Strauss\Stripe\AccountLink::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\AccountLink::class,
        \GiveDonationBlock\Strauss\Stripe\AlipayAccount::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\AlipayAccount::class,
        \GiveDonationBlock\Strauss\Stripe\ApplePayDomain::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\ApplePayDomain::class,
        \GiveDonationBlock\Strauss\Stripe\ApplicationFee::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\ApplicationFee::class,
        \GiveDonationBlock\Strauss\Stripe\ApplicationFeeRefund::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\ApplicationFeeRefund::class,
        \GiveDonationBlock\Strauss\Stripe\Balance::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Balance::class,
        \GiveDonationBlock\Strauss\Stripe\BalanceTransaction::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\BalanceTransaction::class,
        \GiveDonationBlock\Strauss\Stripe\BankAccount::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\BankAccount::class,
        \GiveDonationBlock\Strauss\Stripe\BillingPortal\Configuration::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\BillingPortal\Configuration::class,
        \GiveDonationBlock\Strauss\Stripe\BillingPortal\Session::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\BillingPortal\Session::class,
        \GiveDonationBlock\Strauss\Stripe\BitcoinReceiver::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\BitcoinReceiver::class,
        \GiveDonationBlock\Strauss\Stripe\BitcoinTransaction::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\BitcoinTransaction::class,
        \GiveDonationBlock\Strauss\Stripe\Capability::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Capability::class,
        \GiveDonationBlock\Strauss\Stripe\Card::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Card::class,
        \GiveDonationBlock\Strauss\Stripe\Charge::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Charge::class,
        \GiveDonationBlock\Strauss\Stripe\Checkout\Session::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Checkout\Session::class,
        \GiveDonationBlock\Strauss\Stripe\Collection::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Collection::class,
        \GiveDonationBlock\Strauss\Stripe\CountrySpec::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\CountrySpec::class,
        \GiveDonationBlock\Strauss\Stripe\Coupon::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Coupon::class,
        \GiveDonationBlock\Strauss\Stripe\CreditNote::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\CreditNote::class,
        \GiveDonationBlock\Strauss\Stripe\CreditNoteLineItem::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\CreditNoteLineItem::class,
        \GiveDonationBlock\Strauss\Stripe\Customer::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Customer::class,
        \GiveDonationBlock\Strauss\Stripe\CustomerBalanceTransaction::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\CustomerBalanceTransaction::class,
        \GiveDonationBlock\Strauss\Stripe\Discount::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Discount::class,
        \GiveDonationBlock\Strauss\Stripe\Dispute::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Dispute::class,
        \GiveDonationBlock\Strauss\Stripe\EphemeralKey::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\EphemeralKey::class,
        \GiveDonationBlock\Strauss\Stripe\Event::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Event::class,
        \GiveDonationBlock\Strauss\Stripe\ExchangeRate::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\ExchangeRate::class,
        \GiveDonationBlock\Strauss\Stripe\File::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\File::class,
        \GiveDonationBlock\Strauss\Stripe\File::OBJECT_NAME_ALT => \GiveDonationBlock\Strauss\Stripe\File::class,
        \GiveDonationBlock\Strauss\Stripe\FileLink::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\FileLink::class,
        \GiveDonationBlock\Strauss\Stripe\Identity\VerificationReport::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Identity\VerificationReport::class,
        \GiveDonationBlock\Strauss\Stripe\Identity\VerificationSession::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Identity\VerificationSession::class,
        \GiveDonationBlock\Strauss\Stripe\Invoice::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Invoice::class,
        \GiveDonationBlock\Strauss\Stripe\InvoiceItem::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\InvoiceItem::class,
        \GiveDonationBlock\Strauss\Stripe\InvoiceLineItem::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\InvoiceLineItem::class,
        \GiveDonationBlock\Strauss\Stripe\Issuing\Authorization::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Issuing\Authorization::class,
        \GiveDonationBlock\Strauss\Stripe\Issuing\Card::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Issuing\Card::class,
        \GiveDonationBlock\Strauss\Stripe\Issuing\CardDetails::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Issuing\CardDetails::class,
        \GiveDonationBlock\Strauss\Stripe\Issuing\Cardholder::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Issuing\Cardholder::class,
        \GiveDonationBlock\Strauss\Stripe\Issuing\Dispute::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Issuing\Dispute::class,
        \GiveDonationBlock\Strauss\Stripe\Issuing\Transaction::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Issuing\Transaction::class,
        \GiveDonationBlock\Strauss\Stripe\LineItem::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\LineItem::class,
        \GiveDonationBlock\Strauss\Stripe\LoginLink::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\LoginLink::class,
        \GiveDonationBlock\Strauss\Stripe\Mandate::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Mandate::class,
        \GiveDonationBlock\Strauss\Stripe\Order::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Order::class,
        \GiveDonationBlock\Strauss\Stripe\OrderItem::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\OrderItem::class,
        \GiveDonationBlock\Strauss\Stripe\OrderReturn::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\OrderReturn::class,
        \GiveDonationBlock\Strauss\Stripe\PaymentIntent::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\PaymentIntent::class,
        \GiveDonationBlock\Strauss\Stripe\PaymentLink::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\PaymentLink::class,
        \GiveDonationBlock\Strauss\Stripe\PaymentMethod::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\PaymentMethod::class,
        \GiveDonationBlock\Strauss\Stripe\Payout::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Payout::class,
        \GiveDonationBlock\Strauss\Stripe\Person::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Person::class,
        \GiveDonationBlock\Strauss\Stripe\Plan::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Plan::class,
        \GiveDonationBlock\Strauss\Stripe\Price::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Price::class,
        \GiveDonationBlock\Strauss\Stripe\Product::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Product::class,
        \GiveDonationBlock\Strauss\Stripe\PromotionCode::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\PromotionCode::class,
        \GiveDonationBlock\Strauss\Stripe\Quote::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Quote::class,
        \GiveDonationBlock\Strauss\Stripe\Radar\EarlyFraudWarning::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Radar\EarlyFraudWarning::class,
        \GiveDonationBlock\Strauss\Stripe\Radar\ValueList::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Radar\ValueList::class,
        \GiveDonationBlock\Strauss\Stripe\Radar\ValueListItem::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Radar\ValueListItem::class,
        \GiveDonationBlock\Strauss\Stripe\Recipient::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Recipient::class,
        \GiveDonationBlock\Strauss\Stripe\RecipientTransfer::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\RecipientTransfer::class,
        \GiveDonationBlock\Strauss\Stripe\Refund::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Refund::class,
        \GiveDonationBlock\Strauss\Stripe\Reporting\ReportRun::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Reporting\ReportRun::class,
        \GiveDonationBlock\Strauss\Stripe\Reporting\ReportType::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Reporting\ReportType::class,
        \GiveDonationBlock\Strauss\Stripe\Review::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Review::class,
        \GiveDonationBlock\Strauss\Stripe\SetupAttempt::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\SetupAttempt::class,
        \GiveDonationBlock\Strauss\Stripe\SetupIntent::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\SetupIntent::class,
        \GiveDonationBlock\Strauss\Stripe\ShippingRate::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\ShippingRate::class,
        \GiveDonationBlock\Strauss\Stripe\Sigma\ScheduledQueryRun::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Sigma\ScheduledQueryRun::class,
        \GiveDonationBlock\Strauss\Stripe\SKU::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\SKU::class,
        \GiveDonationBlock\Strauss\Stripe\Source::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Source::class,
        \GiveDonationBlock\Strauss\Stripe\SourceTransaction::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\SourceTransaction::class,
        \GiveDonationBlock\Strauss\Stripe\Subscription::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Subscription::class,
        \GiveDonationBlock\Strauss\Stripe\SubscriptionItem::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\SubscriptionItem::class,
        \GiveDonationBlock\Strauss\Stripe\SubscriptionSchedule::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\SubscriptionSchedule::class,
        \GiveDonationBlock\Strauss\Stripe\TaxCode::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\TaxCode::class,
        \GiveDonationBlock\Strauss\Stripe\TaxId::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\TaxId::class,
        \GiveDonationBlock\Strauss\Stripe\TaxRate::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\TaxRate::class,
        \GiveDonationBlock\Strauss\Stripe\Terminal\ConnectionToken::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Terminal\ConnectionToken::class,
        \GiveDonationBlock\Strauss\Stripe\Terminal\Location::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Terminal\Location::class,
        \GiveDonationBlock\Strauss\Stripe\Terminal\Reader::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Terminal\Reader::class,
        \GiveDonationBlock\Strauss\Stripe\ThreeDSecure::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\ThreeDSecure::class,
        \GiveDonationBlock\Strauss\Stripe\Token::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Token::class,
        \GiveDonationBlock\Strauss\Stripe\Topup::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Topup::class,
        \GiveDonationBlock\Strauss\Stripe\Transfer::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\Transfer::class,
        \GiveDonationBlock\Strauss\Stripe\TransferReversal::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\TransferReversal::class,
        \GiveDonationBlock\Strauss\Stripe\UsageRecord::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\UsageRecord::class,
        \GiveDonationBlock\Strauss\Stripe\UsageRecordSummary::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\UsageRecordSummary::class,
        \GiveDonationBlock\Strauss\Stripe\WebhookEndpoint::OBJECT_NAME => \GiveDonationBlock\Strauss\Stripe\WebhookEndpoint::class,
    ];
}
