name: Deploy to WordPress.org

on:
    release:
        types: [ released ]

jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/wp-org-release.yml@master
        with:
            wp_org_slug: donation-block-for-stripe-by-givewp
            zip_name: donation-block-for-stripe-by-givewp
            text_domain: donation-form-block
        secrets:
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SLACK_ANNOUNCEMENT_WEBHOOK: ${{ secrets.SLACK_ANNOUNCEMENT_WEBHOOK }}
